# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/messages.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'runtime/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16runtime/messages.proto\x12\x07runtime\"z\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x13\n\x0bscript_path\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61ta_size_mb\x18\x04 \x01(\x02\x12\x1c\n\x14scheduled_start_time\x18\x05 \x01(\t\"b\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1a\n\x12\x65xecution_time_sec\x18\x03 \x01(\x02\x12\x15\n\rerror_message\x18\x04 \x01(\t2M\n\x0eTaskDispatcher\x12;\n\x0c\x44ispatchTask\x12\x14.runtime.TaskRequest\x1a\x15.runtime.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=35
  _globals['_TASKREQUEST']._serialized_end=157
  _globals['_TASKRESPONSE']._serialized_start=159
  _globals['_TASKRESPONSE']._serialized_end=257
  _globals['_TASKDISPATCHER']._serialized_start=259
  _globals['_TASKDISPATCHER']._serialized_end=336
# @@protoc_insertion_point(module_scope)
